### ISSUE TITLE
关于tproxy 透明代理的使用问题
这个工具非常好，可以把tcp分隔为两部分，但是没有做到完全透明，经过测试，客户端感觉不到pep存在，但是服务端收到的消息是可以感知pep存在的，无法获取客户端ip，如何结合tproxy工具，实现完全透明呢

### ISSUE THREAD

**Issue by jzbg** [Chirfen/pepsal6#1]

**Comment by Chirfen** [comment]
您好，感谢对pepsal6项目的关注，也感谢您的信赖和来信。

pepsal原项目的[文档](https://sourceforge.net/projects/pepsal/files/Documentation_PDF/PEPsal_%20A%20TCP%20Performance%20Enhancing%20Proxy%20for%20Satellite%20Links/pepsal.pdf/download)中确实也说明了其服务器无法感知客户端IP地址的局限性。
很抱歉，我对tproxy并不熟悉，我不确定其是否能够实现“服务器感知客户端IP地址”的透明性。
不过好消息是，tproxy类功能对网络报文的处理能力（截获、转交到应用层进行其他处理、再返回到内核）与pepsal(6)类似，都是基于iptables（特别是其中的PREROUTING链） 完成的。
因此，您或许可以从掌握iptables (ip6tables) 和 tproxy实现（[1](https://github.com/kristrev/tproxy-example) 、[2](https://wiki.squid-cache.org/Features/Tproxy4)  ）开始，参考或者基于pepsal6进行改造/升级开发。

还需要注意的是，您应当需要保证从server到client IP的路由过程中将经过您的pep节点，以保证该传输过程能正常运行。

（该消息此前已经通过私人信件回复给提出issue的同志，现在也借此暂时close这个issue。）
如果您后续有新的问题或者进展，请随时提出issue，也更欢迎提出PR。
祝好
